name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up JDK (assuming you're using Java)
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # You can also use 'zulu' or other supported distributions
          java-version: '11'

      # Cache SonarQube dependencies
      - name: Cache SonarQube dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}  # Adjust for your project type
          restore-keys: |
            ${{ runner.os }}-sonar-

        # Run SonarQube scan using Docker
      - name: Run SonarQube Scan (using Docker)
        run: |
          docker run --rm \
            -v $(pwd):/usr/src \
            sonarsource/sonar-scanner-cli:latest \
            sonar-scanner \
              -Dsonar.projectKey=sonarqube \
              -Dsonar.projectName="sonarqube" \
              -Dsonar.projectVersion=1.0 \
              -Dsonar.sources=src \
              -Dsonar.host.url=http://65.0.117.200:9000 \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
