name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up JDK (assuming you're using Java)
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # You can also use 'zulu' or other supported distributions
          java-version: '11'

      # Cache SonarQube dependencies
      - name: Cache SonarQube dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}  # Adjust for your project type
          restore-keys: |
            ${{ runner.os }}-sonar-

        # Install SonarQube Scanner manually
      - name: Install SonarQube Scanner
        run: |
          # Download the latest version of SonarQube Scanner from GitHub
          wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/7.0.2.4839/sonar-scanner-cli-7.0.2.4839-linux.zip
          unzip sonar-scanner-cli-7.0.2.4839-linux.zip -d $HOME
          export PATH=$HOME/sonar-scanner-7.0.2.4839-linux/bin:$PATH

      # Run SonarQube scan
      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=sonarqube \
            -Dsonar.projectName="sonarqube" \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=src \
            -Dsonar.host.url=http://65.0.117.200:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

